### ISSUE TITLE
Inconsistent versionning after intermediary commit

### ISSUE THREAD

**Issue by jeantil** [sbt/sbt-git#93] opened 2015-07-15 12:12 UTC
With a git base version at 0.1in a new repository with one commit 
I expect the version to be 0.1-xxxxxxxxxx where xxxxxxxxxx  is the sha1 of the commit

If I tag the commit v1.0.0,
I expect the version to be 1.0.0

If I add a file without committing,
I expect the version to be 1.0.0-SNAPSHOT

If I commit the newly added file (and get the new sha1 yyyyyyyy)
I expect the version to be 1.0.0-yyyyyyyy or 1.0.0-yyyyyyy-SNAPSHOT 

This fails and reverts back to 0.1-yyyyyyyy

Following is an sbt-test test case for the issue , it fails on line 25 with a version which has reverted to 0.1-yyyyyyyy instead of 1.0.0-yyyyyyyy or 1.0.0-yyyyyyyy-SNAPSHOT or maybe 1.0.0-SNAPSHOT

> git init
> git config user.email "test@jsuereth.com"
> git config user.name "Tester"
> git add README.md
> git commit -m "test"
> $ copy-file changes/build.sbt build.sbt
> reload
> inspect version
> checkVersionStartsWith 0.1
> git add build.sbt
> git commit -m"v1.0.0"
> git tag v1.0.0
> reload
> inspect version
> checkVersion 1.0.0
> $ copy-file changes/change1.txt change1.txt
> git add change1.txt
> reload
> inspect version
> checkVersionStartsWith 1.0.0
> checkSnapshotVersion
> git commit -m"v1.0.1"
> reload
> inspect version
> checkVersionStartsWith 1.0.0

**Comment by oliverlockwood** [comment] 2017-06-13 15:50
I came across this while digging this week.

The problem is that the `gitCurrentTags` settings only looks for tags matching the commit at HEAD.
This is caused by the matching logic [here](https://github.com/sbt/sbt-git/blob/master/src/main/scala/com/typesafe/sbt/git/JGit.scala#L67).

I've put together a candidate fix in #135 for discussion.

**Comment by dcecile** [comment] 2018-06-08 11:46
@oliverlockwood @dwijnand With #149 merged, is this issue resolved now?

**Comment by dcecile** [comment] 2018-06-08 12:13
@oliverlockwood @dwijnand Was #149 PR the replacement for #135 PR? If so, now that #149 is merged, is this issue (intermediary commits) now resolved?

**Comment by oliverlockwood** [comment] 2018-06-08 12:35
@dcecile It depends how you look at it 😄

The exactly issue raised by @jeantil is not directly fixed, because as per my https://github.com/sbt/sbt-git/issues/93#issuecomment-308161806 above, there's still direct checking against tags matching the current commit, instead of a search to find *reachable* tags in the history.

However, if you set `git.useGitDescribe := true`, then this flawed code isn't used; instead, JGit's [enhanced](https://github.com/eclipse/jgit/commits?author=oliverlockwood) `describe` functionality does the work for you.

**Comment by dcecile** [comment] 2018-06-08 23:01
@oliverlockwood OK, thanks for the explanation! :pray:

**Comment by sjfloat** [comment] 2018-10-25 18:06
We're seeing what we believe is related to this. When using `GitVersioning`, a SNAPSHOT version is only generated when there are _uncommitted_ changes.

**Closed** 2020-11-25 12:55 UTC
Labels: Bug
